name: test release commands - delete me

on:
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy-html:
    runs-on: ubuntu-latest

    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write
      pages: write
      id-token: write

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false
      
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download index.yaml from teraslice repo
        run: |
          gh api  -H "Accept: application/vnd.github.v3.raw" \
          repos/terascope/teraslice/contents/helm/helm-repo-site/index.yaml > teraslice-index.yaml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge teraslice's index.yaml
        run: |
          cat index.yaml
          cat teraslice-index.yaml

          # merge index.yaml files
          yq eval-all '. | select(fileIndex == 0) *+ select(fileIndex == 1)' index.yaml teraslice-index.yaml > merged-index.yaml
          cat merged-index.yaml
          
          # remove duplicates and sort by version in descending order          
          yq -i \
            '.entries.teraslice-chart |= unique_by(.version) | \
            .entries.teraslice-chart |= sort_by(.version) | \
            .entries.teraslice-chart |= reverse' \
            merged-index.yaml
          cat merged-index.yaml

          # replace old index.yaml with merged
          mv merged-index.yaml index.yaml

          # remove teraslice-index.yaml so it doesn't get merged
          rm teraslice-index.yaml
          ls -la 
          cat index.yaml